# Generated by Django 5.0.7 on 2025-03-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowersShopApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.CharField(max_length=100),
        ),
    ]
