# Generated by Django 5.0.7 on 2025-03-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowersShopApp", "0002_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="direccion",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
