# Generated by Django 5.0.7 on 2025-03-21 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FlowersShopApp", "0003_alter_users_direccion_alter_users_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="telefono",
            new_name="celular",
        ),
    ]
