# Generated by Django 5.0.7 on 2025-03-22 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FlowersShopApp", "0005_flower"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Flower",
            new_name="Flowers",
        ),
    ]
