# Generated by Django 5.0.7 on 2025-03-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowersShopApp", "0006_rename_flower_flowers"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowers",
            name="imagen",
            field=models.ImageField(default="", upload_to="flowers/"),
        ),
    ]
