# Generated by Django 5.0.7 on 2025-03-22 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FlowersShopApp", "0007_flowers_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowers",
            name="comprador",
        ),
    ]
