# Generated by Django 5.0.7 on 2025-03-22 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FlowersShopApp", "0008_remove_flowers_comprador"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowers",
            name="cantidad",
        ),
    ]
