# Generated by Django 5.0.7 on 2025-03-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowersShopApp", "0009_remove_flowers_cantidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowers",
            name="descripcion",
            field=models.CharField(default="", max_length=300),
        ),
    ]
